name: Check build on master

on:
  push:
    branches: 
      - main

jobs:
  pushbuilder:
    runs-on: ubuntu-latest
    container:
      image: obspher/ubuntu-dev:1.1.4
      env:
        CONAN_USER_HOME: ./shared-conan-cache
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Conan remote
        run: conan remote add origin https://obspherit.jfrog.io/artifactory/api/conan/default-conan

      - name: Conan user
        run: export CONAN_REVISIONS_ENABLED=1;conan user -p cmVmdGtuOjAxOjE3MTIxNDg1NTI6WEJSV25hM0NXRkFQZkdtNmhJMldzRXRHelV5 -r origin obspher@obspher.com

      #- name: Clone conan cache
      #  uses: actions/checkout@v2
      #  with:
      #    repository: RandomOrganizationTest/shared-conan-cache
      #    ref: main
      #    token: ${{ secrets.GHCR_PAT }}
      #    path: ./shared-conan-cache

      - name: Verification dependencies
        run: ls ./shared-conan-cache; pwd;

      - name: Install conan dependencies
        working-directory: ./build
        run: export CONAN_REVISIONS_ENABLED=1;conan install .. --build missing --build cascade --update

      - name: Build package
        working-directory: ./build
        run: export CONAN_REVISIONS_ENABLED=1;conan build ..

      - name: Static analysis
        run:  cppcheck src/ -Iinclude/ --error-exitcode=1 --enable=all --std=c++20 --inline-suppr

      - name: Dynamic analysis on unit tests
        run: echo valgrind --leak-check=full --show-reachable=yes --trace-children=yes --error-exitcode=33 ./build/bin/unit_test

      - name: Export conan package
        run: export CONAN_REVISIONS_ENABLED=1;conan export-pkg . -bf ./build -f

      #- name: Upload on conan server
      #  run: export CONAN_REVISIONS_ENABLED=1;conan upload ${{steps.conan_infos.outputs.name}}/${{steps.conan_infos.outputs.version}}

      - name: Push to conan cache
        uses: ad-m/github-push-action@master
        with:
          repository: RandomOrganizationTest/shared-conan-cache
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GHCR_PAT }}
        env:
          ARTIFACT_NAME: shared-conan-cache
          ARTIFACT_PATH: /home/conan/.conan/data