name: Shared Cache

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Init repsitory
      run: |
        mkdir temp
        cd temp
        echo 'init' > init.temp
        cd ..

    - name: Artifact dependencies
      uses: actions/upload-artifact@v2
      with:
        path: temp
        name: shared-conan-artifact
